 INSERT INTO Categorie(label) VALUES ('.NET, ASP, C#');
 INSERT INTO Categorie(label) VALUES ('Adobe : Flash, Flex, Air');
 INSERT INTO Categorie(label) VALUES ('Agile / Scrum');
 INSERT INTO Categorie(label) VALUES ('Angular');
 INSERT INTO Categorie(label) VALUES ('Application Facebook');
 INSERT INTO Categorie(label) VALUES ('Arduino');
 INSERT INTO Categorie(label) VALUES ('Back-end');
 INSERT INTO Categorie(label) VALUES ('Bases de données (SGBD)');
 INSERT INTO Categorie(label) VALUES ('C, C++');
 INSERT INTO Categorie(label) VALUES ('Coldfusion');
 INSERT INTO Categorie(label) VALUES ('Conception API');
 INSERT INTO Categorie(label) VALUES ('Cordova phonegap');
 INSERT INTO Categorie(label) VALUES ('Crypto et blockchain');
 INSERT INTO Categorie(label) VALUES ('Création application Android');
 INSERT INTO Categorie(label) VALUES ('Création application iPhone');
 INSERT INTO Categorie(label) VALUES ('Création application mobile');
 INSERT INTO Categorie(label) VALUES ('Delphi');
 INSERT INTO Categorie(label) VALUES ('Django');
 INSERT INTO Categorie(label) VALUES ('Docker');
 INSERT INTO Categorie(label) VALUES ('Framework (Symfony, Zend...)');
 INSERT INTO Categorie(label) VALUES ('Frameworks JavaScript');
 INSERT INTO Categorie(label) VALUES ('Front-end');
 INSERT INTO Categorie(label) VALUES ('Full-stack');
 INSERT INTO Categorie(label) VALUES ('Gestion de projet');
 INSERT INTO Categorie(label) VALUES ('Ionic');
 INSERT INTO Categorie(label) VALUES ('J2EE, JSP');
 INSERT INTO Categorie(label) VALUES ('Java');
 INSERT INTO Categorie(label) VALUES ('JavaScript');
 INSERT INTO Categorie(label) VALUES ('Jeux vidéos');
 INSERT INTO Categorie(label) VALUES ('Laravel');
 INSERT INTO Categorie(label) VALUES ('Linux');
 INSERT INTO Categorie(label) VALUES ('Lua');
 INSERT INTO Categorie(label) VALUES ('Node.js');
 INSERT INTO Categorie(label) VALUES ('Objects connectés, IoT');
 INSERT INTO Categorie(label) VALUES ('PHP, MySQL');
 INSERT INTO Categorie(label) VALUES ('Perl');
 INSERT INTO Categorie(label) VALUES ('Programmation statistique (MATLAB, R, SAS)');
 INSERT INTO Categorie(label) VALUES ('Python');
 INSERT INTO Categorie(label) VALUES ('React');
 INSERT INTO Categorie(label) VALUES ('Ruby on Rails');
 INSERT INTO Categorie(label) VALUES ('Smartwatches');
 INSERT INTO Categorie(label) VALUES ('Visual Basic, MS Office');
 INSERT INTO Categorie(label) VALUES ('Windev, Webdev');
 INSERT INTO Categorie(label) VALUES ('Windows');
 INSERT INTO Categorie(label) VALUES ('Xamarin');
 INSERT INTO Categorie(label) VALUES ('jQuery');
 INSERT INTO Categorie(label) VALUES ('macOS');
 INSERT INTO Categorie(label) VALUES ('Électronique embarquée');